name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: Run tests
        env:
          NODE_ENV: test
        run: |
          yarn test
